### ISSUE TITLE
DC element term names capitalization

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/metadata#103]
very minor comment. Should the dc element term names not be uncapitalized? (dc:creator, dc:contributor, dc:subject, dc:rights)?

**Comment by zschoenb** [comment]
You're absolutely right. Thanks for the catch. I'm mortified by these... aberrations! Will change promptly.

**Comment by johnhuck** [comment]
Well, they do look like they could be class names. I'm sure you were just testing to see if we were paying attention ;-)
