### ISSUE TITLE
Jupiter Works renamed to Items

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/metadata#106]
More of an FYI than a bug, but Works were renamed to Items in Jupiter, so I think there are some spots in the dictionary that will need to be updated to reflect that. No rush, though.

**Comment by zschoenb** [comment]
For example.... PCDM:Works is now PCDM:Items

**Comment by mbarnett** [comment]
Ah no, Jupiter Items are PCDM:Works. This probably only impacts a few specific spots referencing jupiter:work, like in https://github.com/ualbertalib/metadata/blob/3250d20ea712607fe5413075628f820911c0dcb2/data_dictionary/Jupiter%20Profile%20Template.md

`jupiter:Work (Generic) < pcdm:Object (works:Work)`

**Comment by zschoenb** [comment]
Danoosh, could you go through the template and replace any instance of "jupiter:Work" with "jupiter:Item"

**Comment by cwant** [comment]
@mbarnett I guess one other complication:  within the object store, the 'hasModel' would have value 'IRItem' instead of 'Item'. Similar for 'IRCommunity', 'IRCollection'. I don't know how this will influence the data dictionary.

**Comment by danydvd** [comment]
Done.

**Comment by mbarnett** [comment]
@cwant I don't know if it does. `hasModel` is less "descriptive metadata" than "technical limitation of ActiveFedora that happens to manifest itself in a special namespace of system-related junk that, as far as I can tell, the data dictionary has never concerned itself with".

It's also terribly confusing in metadata conversations insofar as the word "model" in `hasModel` means "Ruby class name" and not anything to do with PCDM or metadata models.

**Comment by mbarnett** [comment]
(we had a discussion about it a couple of months ago that went nowhere because we all meant something different by "model")

**Comment by zschoenb** [comment]
ideally, would we not have Ruby class names that reflect names we use in our object store, at least at the highest level of abstraction (i.e. the "item" vis a vis the "work") and the converse?

**Comment by mbarnett** [comment]
The path of least resistance is to have the Ruby class name reflect how its presented in the user interface and how the stakeholders frame things (hence, since Leah and Sonya decided to phrase the UI in terms of Items, we renamed the Ruby class accordingly). So Ruby class names *do* correspond to objects in the day store: Items-the-Ruby-class correspond to Items-the-Fedora-Object.

`hasModel` is an implementation detail that needs to exist for technical reasons in the stack, but it's not something that can or should be focused on directly. It's an artifact of using Ruby and Fedora together, and if there were a way to keep implementation book-keeping information separate from descriptive-metadata in Fedora, it wouldn't need to exist at all. As such I'd strongly encourage people to not care about it. Upgrades to the stack could change it to a long string of numbers tomorrow without impacting anything that anyone cares about.

**Comment by zschoenb** [comment]
thumbs up. thx for the explanation.

**Comment by zschoenb** [comment]
closed the issue as we've changed jupiter:work to jupiter item. @danydvd
