### ISSUE TITLE
Make thesis objects a subclass of IRItem

### ISSUE THREAD

**Issue by zschoenb** [ualbertalib/metadata#111]
As per discussions with @sfarnel and @mbarnett, the following changes will be made to the data model.

1. Thesis items will no longer contain a dcterms:type property
2. Thesis items will, instead, be demarcated by `rdf:type bibo:thesis`
3. Generic items will no longer permit dcterms:type "Thesis" as a possible value

The above changes need to be applied to:
- [x] PCDM template
- [x] Ontology
- [x] Profile editor

**Comment by danydvd** [comment]
PCDM template now points to the profiles.md.
