### ISSUE TITLE
Jupiter profile template

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#116]
I think it would be worthwhile to slim down the model to remove specific details on metadata and instead point to the data dictionary so that we don't have to try and keep that part of the model up to date. Let's discuss.

**Comment by danydvd** [comment]
I removed the tables for "community", "collection", "generic" and "thesis" and link them to the corresponding readme file in the data dictionary. We can write a script to pull everything from the json files and populate the tables, but it will only display redundant data.

**Comment by sfarnel** [comment]
thanks @danydvd looks good!
