### ISSUE TITLE
Sort out Jupiter Core temporary namespace

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/metadata#119]
This is a ticket from https://github.com/ualbertalib/jupiter/issues/167

We currently have introduced some properties that are not defined in the data dictionary for application development:
    - visibility - as we decide not to use the Hydra's separate objects to save for permissions. the visibility will be a property on the object itself - this will impact the migration as well. 
    - owner - the information used to be kept in separate object as well, same as above. 
    - record_created_at - we could reuse model:createdDate or current date_uploaded for this predicate? this will be the date to track the first ingestion datestamp, whatever system the object was first uploaded in. Could you please advise the preferred predicate?

In the past we have introduced our own namespaces for ualterms, if some of these don't have an existing namespace we could name to, could you please advise which ualterms these predicates should belong?

**Comment by weiweishi** [comment]
@sfarnel Could we have a quick discussion on Tuesday to follow up on this? Thank you.

**Comment by sfarnel** [comment]
absolutely @weiweishi will also ask @zschoenb to attend

**Comment by zschoenb** [comment]
these issues have been broken down and dealt with in subsequent tickets.
