### ISSUE TITLE
Access controls / embargo

### ISSUE THREAD

**Issue by zschoenb** [ualbertalib/metadata#120]
- [x] owner predicate 
  - [bibo:owner](http://purl.org/ontology/bibo/owner)
  - maps to HN access controls "write" group under the "agent" property
- [x] visibility predicate
  - visibility will be indicated in Jupiter by the [dcterms:accessRights](http://purl.org/dc/terms/accessRights) property
  - accessRights will point to one of four possible values: "ual:public", "ual:private", "ual:embargo", or "ual:authenticated".
  - These values map to current HN access controls "read" group under the "agent" property
    - the following are mappings for **unembargoed** resources
      - ual:public maps to "http://projecthydra.org/ns/auth/group#public"
      - ual:authenticated maps to "http://projecthydra.org/ns/auth/group#university_of_alberta" or "http://projecthydra.org/ns/auth/group#registered"
      - ual:private maps to remaining read groups
    - **embargoed** resources are mapped using the embargo object:
      - set accessRights to ual:embargo
      - dated for end of embargo through dc:available
      - contain a visibilityAfterEmbargo with an accessRights value (using the same hydra property, unless decided otherwise):
        - values will be mapped "open/open access" to ual:public; "university_of_alberta" to ual:authenticated
      - previously embargoed items will continue to have the hydra:embargoHistory triple
      - these are not recorded in the data dictionary profile, as they relate to HN permissions objects, not to the resource itself, but they will be recorded in the master ontology, as they do apply directly to resources in the Jupiter environment.
- [x] items require a property describing date of object custody in ERA
  -  tbd
- [x] add these changes to the ontology and the profiles.

**Comment by zschoenb** [comment]
@sfarnel your feedback is requested

**Comment by zschoenb** [comment]
@weiweishi @sfarnel several tickets have been created or altered to reflect the recent google drive document on Jupiter migration.

@weiweishi what should be done when a resource has two read groups (i.e. public and authenticated). Does this practice continue?

**Comment by zschoenb** [comment]
[Referenced in Jupiter Github](https://github.com/ualbertalib/jupiter/issues/205)

**Comment by sfarnel** [comment]
Need to confirm that the above can reflect all scenarios, e.g., embargoed item that becomes public after embargo, embargoed item that becomes ualauthenticated after embargo, draft items. (need to confirm relationship between draft and private)

**Comment by zschoenb** [comment]
@sfarnel As I understand it, the visibilityAfterEmbargo predicate is being ported over, and will continue to be used, to indicate whether an item becomes ual:authenticated or ual:public after the item becomes available. Is this also your understanding? I am also unsure what kind of visibility a draft receives (assuming ual:private)?

**Comment by sfarnel** [comment]
@zschoenb that's my understanding as well. draft should be able to be ual:private

**Comment by zschoenb** [comment]
ual:private has become ual:draft. see https://github.com/ualbertalib/metadata/issues/144

**Comment by zschoenb** [comment]
Closed #114, which was the remaining task for this ticket. closing.
