### ISSUE TITLE
Data Dictionary Review

### ISSUE THREAD

**Issue by zschoenb** [ualbertalib/metadata#125]
## Community
- [x] dcterms:description is not required
## Collection
- [x] ual:community (pcdm:memberOf) is
     - required
     - on form
     - searched
     - accepted value is ual:Community
     - datatype is uri
     - displayed
     - not sorted, faceted, or repeated
## Generic
- [x] pcdm:memberOf is 
    - required
    - on form
    - faceted
    - accepted value is pcdm:collection
- [x] dc:created comment describing required formatting (yyyy)
- [x] dcterms:alternative is 
    - not repeating 
    - is searched (or possibly indexed as title, but this should be discussed with Matt first)
- [x] dcterms:contributor is indexed as creator
- [x] dcterms:spatial and dcterms:temporal are indexed as subject, and are themselves not faceted
- [x] dc:license is not faceted
- [x] add mapping for ual:year_created to ual:sort_year
## Thesis
- [x] pcdm:memberOf is 
    - required
    - NOT on form
    - faceted
    - accepted value is pcdm:collection 44558t416
- [x] supervisor
    - not indexed as contributor
    - not searched
    - not faceted
    - displayable
- [x] add mapping for ual:year_created to ual:sort_year

**Comment by zschoenb** [comment]
Re: data dictionary changes to be made @leahvanderjagt @sfarnel

**Comment by sfarnel** [comment]
from @leahvanderjagt 
- [ ] date should be searchable
- [ ] graduation date should be the sorting date for the theses

**Comment by sfarnel** [comment]
@zschoenb @danydvd we will need to review the existing ual:year_created data as it may need to be regenerated (e.g., I think for theses what had been used was date accepted when it should now be graduation date)

**Comment by danydvd** [comment]
I will generate a report of all records that their ual:year_created is from dcterms:AcceptedDate and has a different ual:graduationDate and will discuss the transformation.

**Comment by danydvd** [comment]
report @ [https://docs.google.com/spreadsheets/d/1Ao-LKcAi1DgNaEKwj-QFBwetG_6PUUZwxyZZl3ThgiU/edit#gid=22852487](url)

**Comment by sfarnel** [comment]
@zschoenb need to add to thesis profile the specs for the admin-only thesis deposit form

**Comment by zschoenb** [comment]
any future tasks can be added to a new ticket
