### ISSUE TITLE
update specs for dcterms:identifier

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#127]
as per ualbertalib/jupiter#72 : For item view, I think we may have forgotten to address special identifiers with legacy collections for which we've used DC: identifier. This would include the CompSci reports, the SER reports, and the fish skeletal elements collection. These are not going to be on any form and I don't think they be searchable, but this is data that we now have for sets of items and I think we should display these IDs.

**Comment by zschoenb** [comment]
dcterms:identifier is used 407 times
269 resources use dc:identifier to indicate a dataverse DOI (i.e. https://dx.doi.org/doi:00.0000/DVN/0000)
138 resources use dc:identifier as a repeating property to indicate a fish skeleton id (fsecatalogue: 0000). 43 ids are used in total, repeating between 3 and 9 times per resource.

**Comment by sfarnel** [comment]
@zschoenb the 259 will no longer be relevant on migration as these were all used to capture the DOI from Dataverse metadata. Dataverse comm/coll/items are not being migrated into Jupiter. The others are proper use of the dcterms:identifier So this is all good news!

**Comment by sfarnel** [comment]
SER and TR ids will be moved to dcterms:identifier in migration

**Comment by zschoenb** [comment]
identifier issues have been dealt with in the migration
