### ISSUE TITLE
data dictionary: admin only requirements

### ISSUE THREAD

**Issue by zschoenb** [ualbertalib/metadata#128]
thesis profile will get an "onForm" true for:
 * title
 * author (dissertant)
 * graduation date 
 * dcterms:type (thesis no longer have dcterms:Type, they are automatically typed RDF:type bibo:thesis when created @sfarnel )
 * colelction membership (pcdm:memberOf) ( thesis always belong to "thesis & dissertations" collection: it would be a dropdown of one, is this what is wanted? @sfarnel @leahvanderjagt  )

**Comment by sfarnel** [comment]
thanks @zschoenb for the reminder about thesis as rdf type :)

from the form mockup it looks like it will simply show community and connection name by default

**Comment by sfarnel** [comment]
@zschoenb sorry for confusion as I should have caught this in your initial issue. based on what's in the data dictionary now, the properties currently in 'on form' and 'required' should be swapped. That is, the form should continue to have all of the potential thesis properties but only the four should be required. Sound ok?

**Comment by sfarnel** [comment]
profile looking good. I see that there is a type (requred) just above type and also that under required title is repeated (although the undelying uri is different). Should be the same as title for non-thesis object

**Comment by zschoenb** [comment]
closing as work is done and no outstanding issues appear to be present

**Comment by zschoenb** [comment]
closing as work is done and no outstanding issues appear to be present
