### ISSUE TITLE
Thesis Migration (Nov 15 2017)

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#131]
metadata team to work with @weiweishi on Nov 15 thesis migration as per ualbertalib/UTA#29

**Comment by danydvd** [comment]
@weiweishi I will start the metadata preparation file as soon as I receive the foxml dumps. Should I ask Henry for that??

**Comment by weiweishi** [comment]
thanks @danydvd. File has been sent. Let me know if I can be any further help!

**Comment by danydvd** [comment]
@weiweishi the reports have been added @: [all_embargoedDates as of 2017-11-06](https://docs.google.com/spreadsheets/d/1jCLmLKuWYujEfgV0V6gtea5bO9evaiBHbWb88jM0mM8/edit#gid=1283729186) and [Unembargo: 2017-11-15](https://docs.google.com/spreadsheets/d/1UhdD_XKmkm0UtG33ZkX5Y2Ej6NgQBHHZwrE6qThhX8M/edit#gid=122674372). The unembargo report includes only "Thesis" items. (there were no other types anyway) . 
There 661 items and the transformed files will be sent shortly.
