### ISSUE TITLE
ual:hydraNoid

### ISSUE THREAD

**Issue by zschoenb** [ualbertalib/metadata#132]
Created a temporary parking spot in collection, community, generic, and thesis files to hold the noid from our hydra objects. This property will be formalized and added to the data dictionary.

**Comment by zschoenb** [comment]
remaining work: decide on a final predicate for ual:hydarNoid

**Comment by sfarnel** [comment]
Add ual:hydraNoid to data dictionary

**Comment by zschoenb** [comment]
ual:hydraNoid is in the dictionary.
