### ISSUE TITLE
generate new sort_year from existing dates

### ISSUE THREAD

**Issue by zschoenb** [ualbertalib/metadata#141]
sort_year is extracted from existing dates through the migration process. It is not backward compatible with the old sort_date property.

- [x] remove backward compatibility from generic and thesis profiles
- [x] add sort_year extraction to transformation
- [x] @sfarnel: decide on multi-year items (e.g. 1979-1982 or 1980, 1982, 1986)

**Comment by zschoenb** [comment]
@sfarnel @danydvd where are we on this job?

**Comment by sfarnel** [comment]
I belive these are part of what @danydvd added to the migration script

**Comment by sfarnel** [comment]
I think in these cases it makes the most sense to go with the earliest year.

**Comment by danydvd** [comment]
added sort functionality to the script (the earliest year will be outputted to the sortyear triple)
