### ISSUE TITLE
fedora:CreatedDate

### ISSUE THREAD

**Issue by zschoenb** [ualbertalib/metadata#145]
Pending decision from @leahvanderjagt 
  - <info:fedora/fedora-system:def/model#createdDate> mapped to a new predicate (see below)
  - <http://fedora.info/definitions/v4/repository#lastModified> stays as is
  - <http://fedora.info/definitions/v4/repository#created> removed from migration

Possibile mappings for fedora:CreatedDate:
- dcterm:Issued - "Date of formal issuance (e.g., publication) of the resource."
- ebucore:dateIngested - "The date when the Resource was ingested/acquired in institutional holdings."
- ebucore:dateReleased - "The date when the Resource was first made available to the public for purchase, download, or online access."
- ebucore:dateDistributed - "The date when the Resource was first made available to the public for purchase, download, or online access."

(more to come?)

**Comment by sfarnel** [comment]
@zschoenb let's use ebucore:dateIngested as it seems the most appropriate

**Comment by zschoenb** [comment]
ebucore:dateIngested has been added to the migration and mapped to fedora-info:created. Tthe profiles and ontology have been updated.

**Comment by zschoenb** [comment]
changing dateIngested to map first to `info:fedora/fedora-system:def/model#createdDate` and, if createdDate is not available, to  `http://fedora.info/definitions/v4/repository#created`

**Comment by zschoenb** [comment]
completed
