### ISSUE TITLE
Spike: COAR Recommendations for Next Generation Repositories

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#161]
Review the COAR report (https://www.coar-repositories.org/activities/advocacy-leadership/working-group-next-generation-repositories/) with an eye to the metadata components.

**Comment by zschoenb** [comment]
https://docs.google.com/a/ualberta.ca/document/d/1C1Xec1fJCSv14aWpb3fMBG683EPWpfZkqc2wf6MncWo/edit?usp=sharing

**Comment by zschoenb** [comment]
Recommendation: Investigate implementing ResourceSync and, over the longer term, author entity modeling based heavily on ORCID. ResourceSync appears to be the highly preferred path forward for resource sharing, content aggregation, and batch discovery. Author entity modeling using ORCID appears to be the preferred path forward for enabling a globally networked system of tracking metrics, issuing push/pull event notifications, and integrating with third-party apps, including social media and recommender systems.

**Comment by sfarnel** [comment]
Review and incorporate additional report on Behaviours and Technical Recommendations: https://www.coar-repositories.org/files/NGR-Final-Formatted-Report-cc.pdf

**Comment by zschoenb** [comment]
I'm fairly certain that was the report I reported on above. In the above linked file, following the summary on the first page, I provide an overview of each recommendation from the "behaviours and technical recommendations" in light of our work.

**Comment by sfarnel** [comment]
Great; thanks @zschoenb closing issue and we'll review and bring to the bigger group

**Comment by zschoenb** [comment]
If I can provide greater detail with respect to any of the recommendations, if having more documentation around something specific interests you, please let me know.
