### ISSUE TITLE
OAI for Jupiter

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#163]
- [x] with Jeff A. review specifications for OAI for Jupiter
- [x] make necessary changes to code based on Jupiter data dictionary

**Comment by zschoenb** [comment]
I have made necessary changes to the data dictionary by creating a profile for etdms and one for pmh. I would like to review these with @jefferya as there are a couple of properties that have changed in how they behave, especially the dc:type. See [etdms](https://github.com/ualbertalib/metadata/blob/master/data_dictionary/profile_oai_etdms.md) & [pmh](https://github.com/ualbertalib/metadata/blob/master/data_dictionary/profile_oai_pmh.md). If it helps, these profiles are also json encoded at [etdms-json](https://github.com/ualbertalib/metadata/tree/master/data_dictionary/profiles/oai_etdms/profile.json) and [pmh-json](https://github.com/ualbertalib/metadata/blob/master/data_dictionary/profiles/oai_pmh/profile.json)

**Comment by danydvd** [comment]
@anayram is it OK to close this?

**Comment by anayram** [comment]
As far as I know, yes. I'll close and re-open if anything comes up.
