### ISSUE TITLE
DOI registration for Jupiter

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#164]
[ ] review specs for and implementation of DOIs in HN
[ ] create revised specs based on Jupiter data dictionary

**Comment by johnhuck** [comment]
[Working document](https://docs.google.com/spreadsheets/d/1BlnnuV9Dbp0ieiIHVJ94rZMYoBm359AzybEzKHcsUSk/edit?usp=sharing)

**Comment by johnhuck** [comment]
[Markdown document](https://github.com/ualbertalib/metadata/blob/master/data_dictionary/Jupiter%20DOI%20registration%20mapping%20(EZID).md) with mapping added to Data Dictionary
