### ISSUE TITLE
Report: list of CCID protected items and their community-collections

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#169]
- [x] generate a list of CCID protected items and their community-collections

@danydvd @zschoenb can the two of you work on this? many thanks!

**Comment by danydvd** [comment]
report is available at: [CCID Protected Items](https://docs.google.com/spreadsheets/d/11IDho8pLrYGA0bl4OCrYHblLNyXiiC5B2Bky1Q5Y2Qw/edit#gid=0)

**Comment by sfarnel** [comment]
Thanks @danydvd
