### ISSUE TITLE
TOC link to bibo:owner broken

### ISSUE THREAD

**Issue by cwant** [ualbertalib/metadata#170]
On this page there is a table of contents with a link to `bibo:owner`:

https://github.com/ualbertalib/metadata/blob/master/data_dictionary/profile_access_and_permissions.md

This link is broken because it is missing an 'o', it points to:

https://github.com/ualbertalib/metadata/blob/master/data_dictionary/profile_access_and_permissions.md#bibowner

It should point to:

https://github.com/ualbertalib/metadata/blob/master/data_dictionary/profile_access_and_permissions.md#biboowner

**Comment by sfarnel** [comment]
@zschoenb please review and revise as needed. thanks!

**Comment by zschoenb** [comment]
Fixed.
