### ISSUE TITLE
Report on multi owner objects

### ISSUE THREAD

**Issue by zschoenb** [ualbertalib/metadata#172]
Generate a report on all gillingham items that have more than one owner for @leahvanderjagt @mbarnett  and @weiweishi

**Comment by zschoenb** [comment]
Multi-owner items in ERA:
 * more than one owner, without eraadmin, erahelp, or era@ualberta.ca: 446 resources
 * more than one owner, with one owner being eraadmin, erahelp, or era: 4483 resources (466 of which are collections)
 * number of individual users affected: 5564

see full report: https://github.com/ualbertalib/metadata/blob/master/metadata-wrangling/jupiter%20reports/ownership_of_objects.xlsx
 
@sfarnel @weiweishi @leahvanderjagt

**Comment by mbarnett** [comment]
> number of individual users affected: 5564

Is this discounting all the users only sharing items with admin accounts? Is it possible that some of this is data from some even older migration?

 In production we only have 2703 unique users who have ever logged in since Sufia-based ERA launched.

**Comment by zschoenb** [comment]
I've had to re-do this report several times now because each time I've reissued it, I've caught some bogus admin email in user field. But here's the bottom line. There are approximately, give or take, 700 items in ERA that have more than non-admin user. That's becoming evident. Some might be legacy artifacts or what have you, but most appear to be legitimate multi-owner objects. Tthey are there to be dealt with. I'm going to make sure this report is robust. it won't be done today.

**Comment by zschoenb** [comment]
https://github.com/ualbertalib/metadata/blob/master/metadata-wrangling/jupiter%20reports/ownership_of_objects.xlsx

**Comment by sfarnel** [comment]
Thanks @zschoenb 
@leahvanderjagt report ready for your review

**Comment by zschoenb** [comment]
@leahvanderjagt I just pushed some additional revisions.

**Comment by zschoenb** [comment]
@leahvanderjagt have I missed your instructions somewhere on what to do with the remaining non-admin multi-author items? Or are the instructions still pending?

**Comment by sfarnel** [comment]
@leahvanderjagt @weiweishi apologies if I've forgotten but do we have a final decision on how to handle these? (i.e., which owner to select and how to track others owners?) I have a feeling we discussed this but I can't seem to find the notes/ thanks!

**Comment by zschoenb** [comment]
Work completed. See https://github.com/ualbertalib/metadata/issues/173 for an explanation
