### ISSUE TITLE
flag test items

### ISSUE THREAD

**Issue by zschoenb** [ualbertalib/metadata#195]
audit the production triple store for instances of 'test' items. generate a report.

**Comment by zschoenb** [comment]
@sfarnel Is this audit report still relevant considering these objects have been mediated by the folks downstairs? Or are there remaining test items that need to be flagged? Also, is it possible that DI folks have edited those items and the changes are not yet available to see in the triplestore?

**Comment by sfarnel** [comment]
@zschoenb seems these will be handled by di staff; closing for now.
