### ISSUE TITLE
Rdf:type in data dictionary

### ISSUE THREAD

**Issue by zschoenb** [ualbertalib/metadata#201]
Documenting RDF:type accepted values in the data dictionary needs to be looked at. This is pressing because currently we are not seeing bibo:thesis or ual:Community in the data dictionary.

Solution:
For each object type, perform a query on all distinct occurrences of rdf:type on the object type. Include any additional new types for jupiter and remove any deprecated types for the migration to jupiter. Add these types as "accepted values" to each item type in the dd triplestore. Make sure that these accepted values are being expressed in the data dictionary profiles.

**Comment by zschoenb** [comment]
1) add an exception to the if statement at line 144 in profiler.py which allows for rdf:type annotations to be printed on the profile, even though it is not "onform=true".
2) add ual:community, pcdm:collection, pcdm:object (etc.) to rdf:type on each object type in the triple store.

**Comment by danydvd** [comment]
The work is completed with [Merged PR](https://github.com/ualbertalib/metadata/commit/a21e46f751195cdbe45b30bbefe145060f2cf192)
