### ISSUE TITLE
Audit migrated data in triplestore-test

### ISSUE THREAD

**Issue by danydvd** [ualbertalib/metadata#227]
Ensure all data has been properly migrated in the sample data in [triplestore](http://triplestore-test.library.ualberta.ca:8080/blazegraph) 

**Dataset stats:** 16 IRFileSet, 20 IRItem, 235 IRCollection, 0 IRCommunity

**Reason for checking the following predicates is that they were either transformed during migration or are new in Jupiter**

- [x] ualdate:sortyear
- [x] dcterms:created
- (8049g674c dcterm:type:Report) does not have a date (No date was provided in the migration package). refer to the report in #130 
- [x] ual:graduationDate
- [x] ontoware:institution
- No Thesis in the sample
- [x] bibo:owner
- values are replaced by numbers (e.g. b9z902z987 should have bibo:onwer as nsercgap@ualberta.ca but it is "4".
- [x] dcterms:accessRights
- [x] dcterms:language
- [x] dcterms:type
- [x] dcterms:license
- [x] pcdm:memberOf
- 6d5700375 memberOf 44558v68t has been repeated 4 times under different uuids:
   1. dde75557-8eb2-4905-883f-30d7d979d997
   2. 712b706e-8ca9-46c3-ab1a-1d3fe4829870
   3. bff07b4a-7b06-4696-911d-043fec8990eb
   4. 1de08176-c345-439a-8725-dbfbd7c0ac92

   The first uuid looks fine but the rest are missing pcdm:memberOf to the collection (44558v68t)
- [x] pcdm:hasMember
- [x] ual:hydraNoid
- [x] bibo:status

@sfarnel @weiweishi please check bibo:owner and pcdm:memberOf.

**Comment by anayram** [comment]
@danydvd @sfarnel 
Quick question, is this the list of items that we should look at post-migration, or is this part of the pre-launch work?

**Comment by danydvd** [comment]
@anayram we can use these along with other properties that you might think are important to audit the post-migration data either in graphDB or the production [triplestore](https://triplestore.library.ualberta.ca:8443/blazegraph/#query)

**Comment by anayram** [comment]
Thanks @danydvd !

**Comment by danydvd** [comment]
This triplestore is no longer alive
