### ISSUE TITLE
POST to GraphDB

### ISSUE THREAD

**Issue by danydvd** [ualbertalib/metadata#244]
GraphDB does not respond to POST queries sent to it via SPARQLWrapper/urllib. These queries (e.g. INSERT, DELETE) are essential for modify the Data Dictionary (http://206.167.181.124:7200/repositories/era-dd) through the [Flask App interface](http://206.167.181.123:8080/). 

Until fixed, please use pure SPARQL in graphDB's to apply updates.

**Comment by piyapongch** [comment]
It does support the POST method. It might be a little bit different from
others. Here is some sample.

Execute the example query with a POST operation:

curl -X POST --data-binary @file.sparql -H "Accept: application/rdf+xml"
  -H "Content-type: application/x-www-form-urlencoded"
  http://localhost:7200/repositories/worker-node

where, file.sparql contains an encoded query:

query=CONSTRUCT+%7B%3Fs+%3Fp+%3Fo%7D+WHERE+%7B%3Fs+%3Fp+%3Fo%7D+LIMIT+10




Piyapong.

**Comment by piyapongch** [comment]
You should be able to use insert and delete statement in the POST query.

Piyapong.

**Comment by danydvd** [comment]
Thank you @piyapongch. I have actually been using curl in command line to POST updates. 

But using SPARQLWrapper (which is the module we are using in our python script in Flask App) returns an read error in urllib

`File "/usr/local/lib/python3.5/dist-packages/SPARQLWrapper/Wrapper.py", line 571, in _query
    response = urlopener(request)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
`

and then graphDB returns this:

`Response:
b'Missing parameter: query'
`

**Comment by piyapongch** [comment]
I think in the python code that creates a POST body not including query=
before the SPARQL. You need to add query= to your query to make it works.

Piyapong.

**Comment by danydvd** [comment]
All functions in the Flask App work fine now. 

- Audit trail is now fixed. 

- User name issue in audit trail is resolved 

- Update/Delete/Insert issues are resolved
