### ISSUE TITLE
Item with no dcterms:accessRights

### ISSUE THREAD

**Issue by danydvd** [ualbertalib/metadata#264]
In post migration data, there are 27 (22 generic and 5 thesis) items that does not have a dcterms:accessRughts triple. 

**Generic**
All of these items are missing at least one required predicate and are incomplete records (see #291). 18 of them has at least one similar record (identical title) in ERA that is a complete record.

- UAT/c0/v8/38/08/c0v838083c - has two similar item (complete record) in ERA (csb397841r, c6h440s85w) which are public.  
- UAT/c2/51/4n/k7/c2514nk75c - has one similar item (complete record) in ERA (cpc289j35n) which is public.  
- UAT/c2/f7/5r/81/c2f75r818x - has one similar item (complete record) in ERA (cjh343s48w) which is public.  
- UAT/c4/45/58/d4/c44558d464 - has one similar item (complete record) in ERA (c1j92g772t) which is public.  
- UAT/c6/68/2x/40/c6682x4096, UAT/c7/w6/2f/83/c7w62f8361, UAT/cc/j8/2k/74/ccj82k743g, UAT/cw/08/92/b0/cw0892b04w and UAT/cx/92/0f/x0/cx920fx06h are similar items - They have one similar items (complete record) in ERA (cn009w253d) which is public. 
- UAT/c6/68/2x/41/c6682x410p - has one similar item (complete record) in ERA (cht24wj56b) which is public.  
- UATt/c6/68/2x/41/c6682x4110 and UAT/ct/b0/9j/58/ctb09j588t are similar - they have one similar item (complete record) in ERA (c79407x35p) which is public.  
- UAT/cd/50/4r/k4/cd504rk47b - has one similar item (complete record) in ERA (c2z10wq41d) which is public.  
- UAT/cm/p4/8s/c9/cmp48sc999 and UAT/cv/x0/21/f2/cvx021f29x
 are similar - they have one similar item (complete record) in ERA (cnp193940b) which is public.   
- UAT/cs/75/26/c7/cs7526c76d - has one similar item (complete record) in ERA (c8k71nh423) which is public.  
- UAT/cw/h2/46/s3/cwh246s37g - has one similar item (complete record) in ERA (cd217qp66f) which is public.  
- UAT/cw/p9/88/k0/cwp988k01x - has one similar item (complete record) in ERA (c7s75dc582) which is public.  
- UAT/br/j4/30/46/brj4304662
- UAT/c0/86/12/n8/c08612n84n
- UAT/cq/52/4j/n9/cq524jn957
- UAT/c5/99/9n/34/c5999n348p

**Thesis**

- UAT/08/61/2q/93/08612q930
- UAT/0z/70/8x/92/0z708x92b
- UAT/cc/r5/6n/11/ccr56n117r
- UAT/cm/32/6m/21/cm326m2186
- UAT/cw/d3/75/w7/cwd375w72w

None of these items have a permission object in pre-migration data (gillingham_20180222 in blazegraph). Therefore, these items would not have a bibo:owner triple either

**Comment by leahvanderjagt** [comment]
Hi @danydvd, please confirm that this string in the first line in the list above is the NOID in hydrnorth?
brj4304662

**Comment by danydvd** [comment]
@leahvanderjagt yes it is the NOID

**Comment by pbinkley** [comment]
Determination based on Anna's investigation:

- 08612q930 - migrate
- 0z708x92b - migrate
- ccr56n117r - do not migrate - final version of the item is in Jupiter 4452dda3-06ea-4c16-82ec-82e05881dbd7
- cm326m2186 - St. Stephens - migrate
- cwd375w72w - do not migrate - cm326m2186 is final version

I'll migrate as soon as the new release is deployed.

**Comment by danydvd** [comment]
Work is complete
