### ISSUE TITLE
Review and potential revision of metadata based on DD

### ISSUE THREAD

**Issue by danydvd** [ualbertalib/metadata#277]
- [x] Check metadata on "Archaeology/Anthropology" collection

**Comment by danydvd** [comment]
The script was changed to fit Jupiter Data Dictionary requirements. Also a new script was added to generate n-triple files for ingest into Jupiter.

**Comment by sfarnel** [comment]
- [ ] Create metadata records for the collection
- [ ] Provide metadata in triple files (like the ones used in the migration) for batch ingest
- [ ] Create batch ingest request in Jupiter Github repo

**Comment by sfarnel** [comment]
Update script to use date from image metadata for date created.

**Comment by danydvd** [comment]
Work is complete and batch ingest request created https://github.com/ualbertalib/jupiter/issues/1104
