### ISSUE TITLE
Add fedora3xml and era1stats types to script and profiles

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata#279]
Add 
`http://terms.library.ualberta.ca/fedora3xml`
and
`http://terms.library.ualberta.ca/era1stats`
to Data Dictionary as `rdf:type` values

**Comment by anayram** [comment]
See [Slack](https://ualbertalib-di.slack.com/archives/C55F96N0G/p1521494968000007)

**Comment by danydvd** [comment]
Migration script is modified to add triples with object value `http://terms.library.ualberta.ca/fedora3xml` or `http://terms.library.ualberta.ca/era1stats` to related objects. 

`<JupiterResource> rdf:type <http://terms.library.ualberta.ca/era1stats>`

**Comment by danydvd** [comment]
Work is finished. Closing
