### ISSUE TITLE
Review documentation and mappings for DOI registration

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#319]
Based on transition from EZID to Datacite

- [ ] review and revise documentation as needed based on https://support.datacite.org/docs/datacite-doi-fabrica
- [ ] communicate any necessary changes to dev team via Github issue

**Comment by sfarnel** [comment]
@johnhuck can this issue be closed?

**Comment by johnhuck** [comment]
@sfarnel I'll be honest, I've lost track of what the context was here. If this was to support the transition to Datacite, I think my last understanding was that the DI plan was to use the Datacite API that mimic-ed EZID, to avoid having to change mappings. If/when we transferred to the more native Datacite API, mappings could be reexamined then. So I think this can be closed. We can always open a new issue later if we need to.

**Comment by sfarnel** [comment]
Thanks @johnhuck Will close for now; we can reopen if needed.
