### ISSUE TITLE
Digitized legacy theses: batch ingest into ERA

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#326]
As part of the project to digitize all UA legacy theses, we need to regularly prepare metadata for batch ingest into ERA. On a quarterly basis
- [x] Generate a list of ual:unicorn values for all UA theses in ERA (Community: Graduate Studies & Research, Faculty of, Collection: Theses and Dissertations)
- [x] Generate a list of all UA theses in IA that have a call_number (which is UAL unicorn id)
- [x] Compare the two lists and generate two new lists: 
- one for unicorn ids that appear on both lists (these will be object overlay only)
- one for unicorn ids that only appear on the IA list (these will be metadata and object ingest)
- [x] Pull marcxml metadata from IA
- [x] Transform marcxml metadata according to Jupiter data dictionary
- [x] include IA identifier to enable correct object harvest from IA
- [x] If possible include Abstract (see #328 for details) 
- [x] Document process

**Comment by danydvd** [comment]
The work is done and a Jupiter compatible migration package was sent to @weiweishi on July 6 2018. Re-open if more work is needed.

**Comment by sfarnel** [comment]
- [ ] Initiate student project to grab abstracts from early theses
- [ ] Add abstracts into triples files as part of migration package
- [ ] Create batch ingest request in Jupiter Github repo

**Comment by danydvd** [comment]
Work is complete and batch ingest request was created https://github.com/ualbertalib/jupiter/issues/1108
