### ISSUE TITLE
Check any new validation rules to be added - Avalon 6

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata#374]
Check any new validation rules to be added

new issue: https://github.com/ualbertalib/avalon/issues/339
ported from: https://github.com/ualbertalib/avalon/issues/162

**Comment by anayram** [comment]
@umarqasim @seanluyk @sfarnel 
Here is a quick list of validation rules for Avalon 6. I looked for github issues related to this but I am not sure I have the complete picture. Would you please help putting together a list of validation rules that we should have for Avalon 6? This would help a lot so that we have smooth migration and audit processes as well as for documentation. Here is the list I gathered.

**Local Avalon validation rules:**
- Genre - required and controlled vocab
- Creator - required
- Language - required and controlled vocab
- Topical Subject - required
- Terms of Use _or_ License URI - required

**Upstream Avalon validation rules:**
- File
- Title
- Date Issued
- Date Issued and Date Created - should be valid according to EDTF
- Bibliographic Id Label - controlled vocabulary and only valid when a Bib Id value is present
- Other Id type - controlled vocabulary and only valid when an Other Id value is present
- Other Id type
- Related Item URL - should be a URL
- Related Item Label - only valid when accompanying a related item URL

**Comment by umarqasim** [comment]
@anayram , 
If we combine these two lists, it will cover all the required fields. Basically there are a total of 8 required metadata elements for a batch ingest and the remaining are value based or conditional validations.

Required Field Validation Rules:

- Title - Required
- Date Issued - Required
- Genre - required and controlled vocab
- Creator - required
- Language - required and controlled vocab
- Topical Subject - required
- Terms of Use or License URI - required
- File - Required

Conditional/Value based Validations:

- Date Issued and Date Created - should be valid according to EDTF
- Bibliographic Id Label - controlled vocabulary and only valid when a Bib Id value is present
- Other Id type - controlled vocabulary and only valid when an Other Id value is present
- Other Id type
- Related Item URL - should be a URL
- Related Item Label - only valid when accompanying a related item URL

**Comment by anayram** [comment]
Thanks, @umarqasim !

**Comment by anayram** [comment]
Decision about validation of person names (creator and contributor fields) - not to validate given that we use the same field to capture organization names.
