### ISSUE TITLE
Graduation date expressed twice

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata#383]
Some theses that have a more specific (yyyy-mm) Graduation Date have the date information appearing twice, e.g. (https://doi.org/10.7939/R3RR1Q16P),
> Graduation date
> 2017-11:Fall 2017

Others seem fine, e.g. (https://doi.org/10.7939/R3SB3XD61),
> Graduation date
> Spring 2018

The display should be like the second example.

From: ualbertalib/jupiter/issues/798

**Comment by anayram** [comment]
@weiweishi @sfarnel @danydvd 

Three patterns are present in graduation dates to be fixed. Here is a quick summary of needed changes:
- [ ] If `yyyy:mm:Season yyyy` - keep substring before `:`
- [ ] If `Spring yyyy` - copy year and add June as month (i.e. `yyyy-06`)
- [ ] If `Fall yyyy` - copy year and add November as month (i.e. `yyyy-11`)

Two questions:
1. @weiweishi do you have a preference on how to fix this issue? For instance, would it be easier that we wait for Anna's work to be finished and then include this fix in a new thesis package along with other pending changes? O do you prefer to use a rake task or another similar process to select the numeric date substring (e.g. 2017-11 in your example)? If the latter, we can reopen the jupiter issue (ualbertalib/jupiter/issues/798).
2.  Could this problem be related to the requirement to _capture_ the numeric date in the metadata but _display_ the season date in the public interface? We believe that was the agreed behaviour but I could not find a related ticket in the hydranorth or jupiter repos.

**Comment by weiweishi** [comment]
@anayram I'd prefer to maybe have a rake task or something to run through the console to update the information. I know Anna's work has been delayed by other priorities, and may take some time to complete. It also ties with the grand audit - so if we could fix this independently, we'd be able to fix this sooner. But if it's too much trouble for your team we can reevaluate. Do you want to quickly chat about this?

**Comment by anayram** [comment]
Update: @anayram to prepare the data and send over to @weiweishi to fix via rake task.

**Comment by anayram** [comment]
@weiweishi shared fixed data for rake task via google drive.
Thank you!

**Comment by weiweishi** [comment]
Thank you very much Mariana!


*Weiwei Shi*Digital Initiative Applications Librarian

2-10L Cameron Library, University of Alberta
780-492-7802  |  weiwei.shi@ualberta.ca
*"The University of Alberta respectfully acknowledges that we are situated
on Treaty 6 territory, traditional lands of First Nations and Métis
people."*
