### ISSUE TITLE
Review ERA data (Jupiter v1.2.3) re: conference paper item type

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#406]
Review migrated data (in triplestore and in ERA public interface) to confirm correct use of item type as reported in ualbertalib/jupiter/issues/789

**Comment by danydvd** [comment]
Here is report of item types (dcterms:type) in the [Triplestore](http://triplestore.library.ualberta.ca:8080):

[dcterms:type_20180927](https://docs.google.com/spreadsheets/d/1ygsCaLCT50wLdRD3QgT1flY9X7DLKrP1qn5O_KUirqc/edit?usp=sharing)

They all seems to be fine except for the "Conference Paper" which is being investigated in ualbertalib/jupiter#820

**Comment by danydvd** [comment]
Work is complete
