### ISSUE TITLE
Thesis metadata migration specs

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata#43]
A few questions on thesis-related specs (part of #20 and #35 ):
@sfarnel 
What datatype to add to graduationdate?
If we split out department, what predicate should we use to capture it?
In the case of thesis: grantor: what URI should I add? http://ualberta.ca/?

From [ERA Metadata Migration spreadsheet](https://docs.google.com/spreadsheets/d/1twJvO-oEPvaSYL8HSqEf892t6-a8wUEclGN6CgKgdsI/edit?pli=1#gid=0):

ERA | HydraNorth | Notes
------------ | ------------- | -------------
eraterms:graduationdate	| ualterms:graduationdate | add datatype
eraterms:specialization | ualterms:specialization | convert to URIs? clean up strings
eraterms:trid | ualterms:trid |  
thesis:contributor role="advisor" | marcrel:ths | would be nice to split out Dep't?
thesis:contributor role="committeemember" | ualterms:thesiscommitteemember | would be nice to split out Dept?
thesis:discipline | vivo:AcademicDepartment | convert to URIs? clean up strings
thesis:grantor | marcrel:dgg | add UofA URI
thesis:level | ualterms:thesislevel | if still needed? clean up strings
thesis:name | bibo:ThesisDegree | convert to URIs? (will need to create) clean up strings

**Comment by sfarnel** [comment]
- Datatype for graduation date should be consistent with application of datatype to other dates; see http://www.w3.org/TR/xmlschema-2/#datatype (date or gYearMonth).
- Splitting out of Dep't would be a longer term goal and tied to individuals as objects in and of themselves
- For thesis:grantor, will need to use University of Alberta pending ualbertalib/HydraNorth#370, ualbertalib/HydraNorth#425, ualbertalib/HydraNorth#426, ualbertalib/HydraNorth#522

**Comment by anayram** [comment]
Specs for migration mapped in migration scripts.
