### ISSUE TITLE
CanLink data - update LOC uri for publisher

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata#435]
In CanLink data we have Publisher defined with property URI
http://id.loc.gov/vocabulary/relators/pub

Correct URI is
http://id.loc.gov/vocabulary/relators/pbl

**Comment by danydvd** [comment]
- [x] The processing scripts was modified to reflect this on new data. 
- [ ] To accomplish this for the current data: Use SPARQL DELETE/INSERT to replace the predicate.
