### ISSUE TITLE
CanLink data - include committee members as person objects

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata#436]
CanLink data is missing committee members information for University of Alberta theses in ERA.

Committee members are available from:
http://terms.library.ualberta.ca/commiteeMember

Thesis advisor is currently mapped
from:
http://terms.library.ualberta.ca/supervisor
to:
http://id.loc.gov/vocabulary/relators/ths

**Comment by danydvd** [comment]
@anayram @sfarnel how does this sound for committee member field?

``` <owl:Class rdf:about="http://vivoweb.org/ontology/core#Committee">
<rdfs:label xml:lang="en">Committee</rdfs:label>
<rdfs:subClassOf rdf:resource="http://xmlns.com/foaf/0.1/Group"/>
<obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">
A group of people organized for a specific purpose (e.g., a reporting or advisory role), often with a charge and for a specific duration
</obo:IAO_0000115>
<obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">
A group of people organized for a specific purpose, whose members are often selected from a larger group to serve for designated periods of time.
</obo:IAO_0000115>
<obo:IAO_0000112 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">
Curriculum Steering Committee; PhD Advisory Committee
</obo:IAO_0000112>
<obo:IAO_0000112 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">
There could be many subclasses such as thesis committee or tenure committee, but these may typically be differentiated via the moniker unless distinct properties become important.
</obo:IAO_0000112>
</owl:Class>

**Comment by sfarnel** [comment]
Thanks @danydvd within this is there a way to label individual members? would the idea be that the committee would then have an identifier that could be linked to from individual members of that committee? we'd want to be able to drill down to the individual (although the ability to see groupings is also interesting)

**Comment by danydvd** [comment]
@sfarnel We can create a Committee object (which is subclass of foaf:Group) and use foaf:member to point to each member. Each member then would have its own object (just like author/adviser objects). Does that sounds OK?

**Comment by sfarnel** [comment]
That sounds great @danydvd!

**Comment by danydvd** [comment]
Here is a sample of new model:

`CANLINK:thesis/b34be774ffa9e55b6d284e973da760cc VIVO:committee 
 CANLINK:committee/f2072128c37103a9e10484cfa3af32b3`


`CANLINK:committee/f2072128c37103a9e10484cfa3af32b3
VOID:inDataset CANLINK:void/canlinkmaindataset ; 
rdf:type foaf:Group ;
PROVwasGeneratedBy CANLINK:runtime/89dc201c252b90dead72e7efa8f62623 ;
foaf:member CANLINK:person/1284c188075537111129ab22715ffbce`

`CANLINK:person/1284c188075537111129ab22715ffbce
VOID:inDataset CANLINK:void/canlinkmaindataset ;
rdf:type foaf:Person ;
PROVwasGeneratedBy CANLINK:runtime/89dc201c252b90dead72e7efa8f62623 ;
foaf:name 'Committee Member name'`

Once the reconciliation process is developed (#438 ), `owl:sameAs` with URIs from VIAF and LC (and probably ORCID) will be added to the person object. 

@sfarnel @anayram does this looks fine?

**Comment by anayram** [comment]
This looks great, @danydvd 

In order to match the person object model, would it be useful (or doable) to also include
`<http://xmlns.com/foaf/0.1/firstName>`
and
`<http://xmlns.com/foaf/0.1/lastName>`
properties?

```
CANLINK:person/1284c188075537111129ab22715ffbce VOID:inDataset  ;
    CANLINK:void/canlinkmaindataset ;
    rdf:type foaf:Person ;
    PROVwasGeneratedBy CANLINK:runtime/89dc201c252b90dead72e7efa8f62623 ; 
    oaf:name 'Committee Member name'<http://xmlns.com/foaf/0.1/firstName> 'someFirstName' ;
    <http://xmlns.com/foaf/0.1/lastName> 'someLastName' .
```

And last, (this is probably not an issue but mentioning it just in case), there is a ':' missing after PROV prefixes

Thanks so much @danydvd , looking great!

**Comment by anayram** [comment]
And one question, when generating the new data I imagine there will be many committee members that already have a person object available in the CanLink dataset. Will this process match those so as to not create redundant persons items?

**Comment by danydvd** [comment]
Thank you @anayram. The firstname and lastname properties will be added to the object if the process can split the name into firstname / lastname strings (this is the case for every person model). 

The process uses a combination of person's name and institution strings to create a md5 hash for any person object. Therefore, if a URI for a person (with work in the same university) already exists, then the same URI will be used. However, if the person has a work (author/adviser/committee member) in another university, then a new URI will be assigned.

**Comment by anayram** [comment]
Thanks, @danydvd !

**Comment by sfarnel** [comment]
Thanks @danydvd and @anayram this is looking really great!

**Comment by danydvd** [comment]
The model has been created and data updated
