### ISSUE TITLE
CanLink data - Change subject modelling 

### ISSUE THREAD

**Issue by danydvd** [ualbertalib/metadata#443]
Currently if a subject if found in LSCH, the lc URI will be the value of dcterms:subject. 

The current solr index can't index these URI (the URI itself can be indexed but the string value would be something like "http://id.loc.gov/authorities/subjects/sh85104660.html" which is not useful for search).

**Proposed Change:** create a canlink URI for all subject and added the string value as rdfs:label and if any matches in LSCH or CSH were found, add them with owl:sameAs. This way we can index the subject string value and use it in search.

@sfarnel @anayram what do you think?

**Comment by anayram** [comment]
This sounds good to me @danydvd, and were you thinking of modelling it as a subgraph just as we have csh? If so we could follow the modelling used for the CSH CanLink graph (I imagine that is what you have in mind) e.g.:
http://206.167.181.235:7200/resource?uri=http:%2F%2Fcanlink.library.ualberta.ca%2Fsubject%2FCaOONL0200C0560

where the CSH subjects were modelled with
skos:prefLabel
skos:altLabel
owl:sameAs
rdf:type http://www.w3.org/2004/02/skos/core#Concept
rdfs:inDataset http://canlink.library.ualberta.ca/subject/canadian-subject-headings

and the rdfs:inDataset could be something like http://canlink.library.ualberta.ca/subject/lc-subject-headings

just my 0.2 cents

**Comment by danydvd** [comment]
@anayram the current version of Canlink does not seem to be connected to CSH subgraph. To me the CSH subgraph looks like a local version of CSH (using Canlink URIs). In order to do it this way we would have to generate a dictionary (a pickle file) of all the subjects in the CSH subgraph like this:

```{canlink/subjects/CaOONL0200C0560:{skos:prefLabel:xyz, skos:altLabel:zyx}, ...}```

We have to use this dict to match subjects in thesis items with the labels and assign the matching URI to the items dcterm:subject;  

```canlink:thesis/4f8a... dcterm:subject canlink:subjects/CaOONL0200C0560```

For lc subjects, we can either follow the same technique as for CSH which means that we would have to create a localized subgraph for lc as well. Or we can create a random UUID and use ```owel:sameAs``` to point to lc URI;

```canlink:thesis/4f8a... dcterm:subject canlink:subjects/UUID```

and 

```
canlink:subjects/UUID 
   rdfs:label 'xyz'
   owl:sameAs http://id.loc.gov/authorities/subjects/xyz.html
   ...
```

I think we should talk about this is more details!

**Comment by anayram** [comment]
We just went through this and in the meantime the subject model we will use is the current subject subgraph where canlink uris are minted and will consult with @sfarnel about whether or not we need to keep the disconnected CSH graph at all given that this not currently used.

**Comment by danydvd** [comment]
The processing scripts has been modified to reflect this.
