### ISSUE TITLE
ERA report

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#449]
In preparation for discussions on ways to improve Google Scholar indexing, generate a report on all ERA items with

- uuid
- status
- content of
-- isVersionOf
-- source
-- relation

**Comment by anayram** [comment]
Done, report available from https://docs.google.com/spreadsheets/d/1j1NxhPW51-h9saNJIiUiUNLzG66MQMlhXLjkyfZ63Zo/edit?usp=sharing

**Comment by anayram** [comment]
Related to #445
