### ISSUE TITLE
CanLink data: enhance keywords with URIs

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#453]
In process work [here](https://drive.google.com/file/d/1io1bYmpIxo4KXOHcybGBJzvlaJCrSJlp/view?usp=sharing)

**Comment by danydvd** [comment]
@sfarnel the current processing script tries to match subject terms to a term in LCSH and CSH (90% matching cutoff level) and add the URI as `owl:sameAs`. 
Do we want to add URIs from the above list first and initiate the current process if the term was not in the list?

**Comment by sfarnel** [comment]
thanks @danydvd yes, as the process was to review the items that didn't already have a URI (so ones that did not match)

**Comment by danydvd** [comment]
Thanks @sfarnel. This has been implemented and tested in both marc and rdf processing scripts. A pickle file was generated and added to `/CanLink/code/website/processing/files/` folder. Once we get a new spreadsheet, we would have to replace it with a newly generate pickle.

**Comment by danydvd** [comment]
Work is complete. Closing
