### ISSUE TITLE
Move urls captured as unicorn ids to dcterms:identifier

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata#50]
Examples:
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk2/ftp04/mq21149.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk2/ftp04/mq21155.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk3/ftp05/mq22701.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk2/ftp04/mq22517.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk2/ftp04/mq22518.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk3/ftp04/mq22575.pdf
unicorn:http://foothillsresearchinstitute.ca/Content_Files/Files/WC/WC_report2.pdf
unicorn:http://carnivorelibrary1.free.fr/NielsenPhDa.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk2/ftp04/mq22511.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk2/ftp04/mq21150.pdf
unicorn:http://foothillsresearchinstitute.ca/Content_Files/Files/WC/WC_report1.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk2/ftp04/mq22514.pdf
unicorn:http://wwwlib.umi.com/dissertations/fullcit/NQ68619
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk2/ftp04/mq21255.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk3/ftp04/mq22569.pdf
unicorn:http://foothillsresearchinstitute.ca/Content_Files/Files/WC/WC_report4.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk3/ftp04/nq21546.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk3/ftp05/mq22699.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk2/ftp04/mq22515.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk3/ftp04/nq22953.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk2/ftp04/mq21152.pdf
unicorn:http://foothillsresearchinstitute.ca/Content_Files/Files/WC/WC_report3.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk2/ftp04/mq22565.pdf
unicorn:http://www.nlc-bnc.ca/obj/s4/f2/dsk2/ftp04/mq21148.pdf

To be reviewed by @sfarnel 
Part of #35

**Comment by anayram** [comment]
Full list here: https://docs.google.com/spreadsheets/d/1NdFv8sgnrG6pPcvS_U7nY4ZR4C8cVFAg3cSa6TWfvR8/edit#gid=2012907233

**Comment by sfarnel** [comment]
let's not bring these over as part of the migration.

On Tue, Aug 25, 2015 at 2:07 PM, Mariana Paredes-Olea <
notifications@github.com> wrote:

> Full list here:
> https://docs.google.com/spreadsheets/d/1NdFv8sgnrG6pPcvS_U7nY4ZR4C8cVFAg3cSa6TWfvR8/edit#gid=2012907233
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ualbertalib/metadata-transforms/issues/50#issuecomment-134722355>
> .
>



-- 
Sharon Farnel
Metadata Coordinator
University of Alberta Libraries
sharon.farnel@ualberta.ca
780-492-3685
