### ISSUE TITLE
Review duplicates

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata#64]
**Bodies and texts, spaces and borders: women re-envision breast cancer**
uuid:e2f23197-0b37-4f69-b3dc-0d460902018b
https://era.library.ualberta.ca/files/q811kk883

uuid:abce26e2-6b32-4655-afa1-1f0c01a01800
uuid:ad91461b-33e1-4b87-a728-c1cd00cc04cb
uuid:fc9e071d-c956-4ee7-992b-51a76fbe0990
uuid:5e0c9893-08d3-4138-b78d-9268fb9e1980
uuid:bc36e502-a3c0-4e5a-87cc-717c88ca3828
uuid:d90165a4-aa7a-4cca-acad-910a0cd3cc72
uuid:79ba71ea-5ab0-4dcc-9c67-4d2070265a30
uuid:0934b04d-1238-44b8-b5f8-7fe97d81badd
uuid:a97d6a14-f50f-4920-8056-fa05578240f6
uuid:6e12ca50-7369-40db-a670-a4898eb33f3c
uuid:b2e24d98-cc99-471f-b766-0b0c5e8d034b
uuid:d20932d7-fdb4-4d2e-b7a8-a9386e429f89
uuid:65d68b0c-f955-440e-bd8f-1fd4d9407657
uuid:b8f53d83-bbb2-4980-a0a6-6c17484024d4
uuid:f8e9092d-c382-4e6b-92f2-4b16e4ee93bd
uuid:c86a685f-969d-412b-93f0-98fa6fc32263
uuid:2c6a5274-fd07-4934-adf6-8e8900cb4085
uuid:5a8c3b6f-426b-4aae-b5f5-dc98f2f4b0e0
uuid:d353f60d-8b68-4048-a55d-5d024b93f1df
uuid:1bd09bd5-3379-4182-8450-8e0ea1e4ebba
uuid:bc37109c-7d24-4dd6-8749-9bd108bb08e6
uuid:d1c0b85d-2b58-43f1-af30-9c0f284a7b1a

**969.55.1 dorsal**
uuid:5ab2b4a1-02ce-47e4-8a78-81aa1182f342
https://era.library.ualberta.ca/files/nc580n18d

uuid:199cd798-5bcd-4b98-9fc9-344f7c3a32df
uuid:9746d84c-accc-4a75-b636-04c7c3b114ab
uuid:7c1b7f21-0417-484d-adb4-3afcfd997b60
uuid:cf2ece02-e45c-4f72-a6dc-81f4ccd16f49
uuid:fb42ae6a-de4f-4f65-b096-7c304f0cbbe9
uuid:2eb943ca-c129-4d67-b4a8-efc95c746192
uuid:f636993a-d22e-4fa4-aa09-e4699a4a3b6a
uuid:195ce58b-f476-4748-9a5a-af1642c0271b
uuid:f9d90178-28f3-4913-b040-57a18aa12884
uuid:15449bd3-9fc0-4e0a-bad6-0ff6228c0beb

**Comment by danydvd** [comment]
All duplicates are removed!
