### ISSUE TITLE
Review Google Scholar 'epic' story and create smaller issues

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/metadata#66]
This is a spike for the metadata team (John) to review the issue https://github.com/ualbertalib/HydraNorth/issues/435, and add new stories to the HydraNorth backlog reflecting work to be done to address Google Scholar requirements for new ERA.

**Comment by sfarnel** [comment]
stories in:
ualbertalib/HydraNorth#848
ualbertalib/HydraNorth#849
ualbertalib/HydraNorth#850
ualbertalib/HydraNorth#851
ualbertalib/HydraNorth#852
