### ISSUE TITLE
Metadata implications/requirements of registering NOIDS as ARKs

### ISSUE THREAD

**Issue by johnhuck** [ualbertalib/metadata#69]
Review the metadata implications and requirements of registering NOIDS as ARKs, as described in:

https://github.com/ualbertalib/HydraNorth/issues/571

Collect background information and add issues and comments as necessary to the main HydraNorth backlog.

**Comment by sfarnel** [comment]
@johnhuck I believe we can close this as it was for assessing the issue and creating issues in the main repo which has been done. can you confirm and close?

**Comment by johnhuck** [comment]
@sfarnel yes, we can. thanks for keeping track.
