### ISSUE TITLE
Metadata implications/requirements of registering DOIs

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#70]
Review the metadata implications and requirements of registering NOIDS as ARKs, as described in:

ualbertalib/HydraNorth#448

Collect background information and add issues and comments as necessary to the main HydraNorth backlog.

**Comment by sfarnel** [comment]
@johnhuck I believe we can close this as it was for assessing the issue and creating issues in the main repo which has been done. can you confirm and close?

**Comment by johnhuck** [comment]
@sfarnel likewise this one is done too. We can make a new issue later for any further work.
