### ISSUE TITLE
Transform Nosotros metadata for ingest into Avalon

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#92]
- [x] Nosotros pt. 1 (materials in IA as of July 2016)
- [x] Nosotros pt. 2 (materials not in IA as of July 2016)

**Comment by zschoenb** [comment]
nosotros metadata is ready for Avalon ingest at [(https://docs.google.com/a/ualberta.ca/spreadsheets/d/1yJJ0JuvJL11uRYMm4kAXQDU9VEHlFj4oNXmV9lRcJaQ/edit?usp=sharing)]... whether metadata reflects all nosotros objects is up for further verification by myself together with @anayram

**Comment by anayram** [comment]
Finished second batch https://docs.google.com/spreadsheets/d/1K6AVhisgTrEbVMOjuwvcPxcD6gP53Uq3GmdqzIQ1rgA/edit?usp=sharing

Structure files at https://github.com/ualbertalib/metadata/tree/master/metadata-wrangling/avalon/nosotros/structure_files_nosotros_se
