### ISSUE TITLE
OAI-ORE for harvesting from ERA

### ISSUE THREAD

**Issue by sfarnel** [ualbertalib/metadata#97]
Investigate OAI-ORE specifications for metadata + object harvesting to understand metadata implications.

See https://www.openarchives.org/ore/

**Comment by sfarnel** [comment]
Looks might be helpful: http://ai2-s2-pdfs.s3.amazonaws.com/231f/3f36d916555b16a617d627b3450702bbe94d.pdf

And this: https://groups.google.com/forum/#!topic/oai-ore/vRhnTCQiVpM

**Comment by johnhuck** [comment]
Here is an [ALA tech report on OAI-ORE](http://login.ezproxy.library.ualberta.ca/login?url=http://search.ebscohost.com/login.aspx?direct=true&db=e000xna&AN=474963&site=eds-live&scope=site). It's a decent general introduction that supplements the primer on the openarchives website. I also have a paper copy if ppl find the occasional random font variations too distracting in the e-book.

**Comment by zschoenb** [comment]
I will add [this presentation](https://smartech.gatech.edu/bitstream/handle/1853/28448/83-378-1-PB.pdf) and [this code4lib article](http://journal.code4lib.org/articles/1062). The presentation presents a higher level overview of mapping ORE to community/collections/items in Dspace. The code4lib article, under 'Fedora export plug-in' and 'Fedora import plug-in' headings describes instructions for parsing the Fedora export RDF with ORE, then reingesting it. They use the RDFLib in python for the parsing, which is what I used to parse the Convocation Hall into RDF. Its an interesting workflow.

**Comment by sfarnel** [comment]
Details from @zschoenb investigations:
Details:
The most common way of making OAI-ORE discoverable is by exposing it through OAI-PMH. This is achieved by essentially pointing the PMH record at the ORE resource map. At least one institution (Texas Digital Library) uses ORE to aggregate resources and exposes those aggregations through PMH. The mechanisms for exposing ORE directly are varied and appear to be overlapping. They include:
1) HTTP 303 redirection (with or without content negotiation)
2) Encoding into XHTML using RDFa
3) Embedding HTML link elements or using custom HTTP response headers
4) Using a “hash URI”
5) Exposure via Atom xml
6) Exposure via a “splash page” or Sitemap (possibly through ResourceSync?)
IMPORTANT: We have not identified a live example of OAI-ORE dissemination in a repository environment through a mechanism other than OAI-PMH. 
Exposing OAI-ORE directly requires LAC to identify which of the above models it prefers (i.e. Atom xml vs RDFa, etc.) We can move forward from there.
Resources:
OAI-ORE through OAI-PMH at Texas Digital Library: https://smartech.gatech.edu/bitstream/handle/1853/28448/83-378-1-PB.pdf and http://ai2-s2-pdfs.s3.amazonaws.com/231f/3f36d916555b16a617d627b3450702bbe94d.pdf
OAI-ORE dissemination:
Witt, Michael (2010). “Object Reuse and Exchange (OAI-ORE)” Library Technology Reports 46:4
ORE 1.0 spec www.openarchives.org/ore/1.0/discovery.
ORE 1.0 spec http://www.openarchives.org/ore/1.0/http#WithMicroformats

**Comment by sfarnel** [comment]
Further info from LAC:
Texas Digital Library is the best working example of the architecture we would be working towards. We have been able to harvest ORE from the University of Regina. Their “Data Provider” Can be found here:
http://ourspace.uregina.ca/oai/request?verb=ListMetadataFormats
It looks tobe using an Atom-serialized ORE ReM for dissemination (and harvesting).

Example from UofR:

<atom:entry xmlns:ore="http://www.openarchives.org/ore/terms/" xmlns:oreatom="http://www.openarchives.org/ore/atom/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:doc="http://www.lyncode.com/xoai" xmlns:atom="http://www.w3.org/2005/Atom" xsi:schemaLocation="http://www.w3.org/2005/Atom http://www.kbcafe.com/rss/atom.xsd.xml">
<atom:id>http://hdl.handle.net/10294/7/ore.xml</atom:id>
<atom:link rel="alternate" href="http://hdl.handle.net/10294/7" />
<atom:link rel="http://www.openarchives.org/ore/terms/describes" href="http://hdl.handle.net/10294/7/ore.xml" />
<atom:link type="application/atom+xml" rel="self" href="http://hdl.handle.net/10294/7/ore.xml#atom" />
<atom:published>2008-02-11T22:05:40Z</atom:published>
<atom:updated>2008-02-11T22:05:40Z</atom:updated>
<atom:source>
<atom:generator>oURspace</atom:generator>
</atom:source>
<atom:title>Policy and practice in education : Vol. 11, No. 1/2</atom:title>
<atom:category label="Aggregation" term="http://www.openarchives.org/ore/terms/Aggregation" scheme="http://www.openarchives.org/ore/terms/" />
<atom:category scheme="http://www.openarchives.org/ore/atom/modified" term="2008-02-11T22:05:40Z" />
<atom:category label="DSpace Item" term="DSpaceItem" scheme="http://www.dspace.org/objectModel/" />
<atom:link rel="http://www.openarchives.org/ore/terms/aggregates" href="http://ourspace.uregina.ca:8080/xmlui/bitstream/10294/7/3/PPE_11_1_2_rev.pdf" title="PPE_11_1_2_rev.pdf" type="application/pdf" length="570191" />
<oreatom:triples>
<rdf:Description xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" rdf:about="http://hdl.handle.net/10294/7/ore.xml#atom">
<rdf:type rdf:resource="http://www.dspace.org/objectModel/DSpaceItem" />
<dcterms:modified>2008-02-11T22:05:40Z</dcterms:modified>
</rdf:Description>
<rdf:Description xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" rdf:about="http://ourspace.uregina.ca:8080/xmlui/bitstream/10294/7/2/license.txt">
<rdf:type rdf:resource="http://www.dspace.org/objectModel/DSpaceBitstream" />
<dcterms:description>LICENSE</dcterms:description>
</rdf:Description>
<rdf:Description xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" rdf:about="http://ourspace.uregina.ca:8080/xmlui/bitstream/10294/7/3/PPE_11_1_2_rev.pdf">
<rdf:type rdf:resource="http://www.dspace.org/objectModel/DSpaceBitstream" />
<dcterms:description>ORIGINAL</dcterms:description>
</rdf:Description>
<rdf:Description xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" rdf:about="http://ourspace.uregina.ca:8080/xmlui/bitstream/10294/7/4/PPE_11_1_2_rev.pdf.txt">
<rdf:type rdf:resource="http://www.dspace.org/objectModel/DSpaceBitstream" />
<dcterms:description>TEXT</dcterms:description>
</rdf:Description>
</oreatom:triples>
</atom:entry>

Questions we've posed:

- will you harvest the ETDMS record for the full metadata record, and then harvest the ORE record in order to retrieve the bitstreams? (i.e., the absence of bibliographic metadata in this ORE record is not a concern)
- do you require handles, or could we use DOIs in the various atom identifier fields?
- in the example http://hdl.handle.net/10294/7/ore.xml doesn't resolve (though http://hdl.handle.net/10294/7 does, as you'd expect). Does this matter?
- do you have suggestions for non-DSpace-based values for rdf:resource? Or do you require the DSpace ones?
- we don't have separate TEXT bitstreams. Would LICENSE and ORIGINAL be sufficient?

@danydvd can you spend some time looking further into the exposure through ATOM xml option?

**Comment by danydvd** [comment]
Here is a summery of what I have found so far on exposure of ORE through Atom

[ORE through Atom](https://docs.google.com/a/ualberta.ca/document/d/13LaxT2zf_X5CpfoVOjyuxaAyUxvlxFYeL2ktffQBYvo/edit?usp=sharing)
